{
 "title": "Twilytics - Mocked Twitter Data",
 "time": { "from": "2019-08-16T17:08:39.000Z", "to": "2021-07-16T19:19:38.000Z" },
 "panels": [
  {
   "title": "Top Trending Twitter Topics",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Key Overall Metrics",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Last 24 Hours",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT frequency, topic from \"trending_topics\";"
    }
   ]
  },
  {
   "title": "Last Week",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT frequency, topic from \"trending_topics\";"
    }
   ]
  },
  {
   "title": "Last Month",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT frequency, topic from \"trending_topics\";"
    }
   ]
  },
  {
   "title": "Last Year",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT frequency, topic from \"trending_topics\";"
    }
   ]
  },
  {
   "title": "Total Change Rates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  max(changerate_berlin) AS \"changerate\"\nFROM changerates\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Max (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  max(changerate_berlin) AS \"changerate\"\nFROM changerates\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Distribution of Topics",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"timestamp\"),\n  topic,\n  frequency\nFROM\n  \"trending_topics\"\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER by\n  frequency DESC;\n"
    }
   ]
  },
  {
   "title": "Average (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(changerate_stuttgart) AS \"changerate\"\nFROM changerates\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Min (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  min(changerate_stuttgart) AS \"changerate\"\nFROM changerates\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Change Rate of Twitter Trends for Berlin & Stuttgart",
   "type": "graph",
   "description": "Example: At the timestamp 2020-07-18 14:00:02 the rate the Twitter trends change in Berlin are 32%.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  changerate_berlin\nFROM changerates\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  changerate_stuttgart\nFROM changerates\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Trend Equality b/w Berlin & Stuttgart (at the Same Time)",
   "type": "graph",
   "description": "Example: At the timestamp 2020-07-18 20:00:01 the Twitter trends of Berlin and Stuttgart match up by 88%",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Trendsetter Stuttgart Compared to Berlin (at Different Times)",
   "type": "graph",
   "description": "Example: At the timestamp 2020-07-18 23:00:01 the trends in Stuttgart match up by 62% with the trends At the timestamp 2020-07-18 22:00:01 in Berlin.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  correlation\nFROM trendsetter_city\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Change Rates",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"changerates\";"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "targets": [
    { "rawSql": "SELECT * FROM cities;" }
   ]
  },
  {
   "title": "Trend Comparison Data",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT * FROM trend_comparison;"
    }
   ]
  },
  {
   "title": "Trendsetter City Data",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"trendsetter_city\";"
    }
   ]
  }
 ]
}