{
 "title": "Twilytics",
 "time": { "from": "2019-08-16T17:08:39.000Z", "to": "2021-07-16T19:19:38.000Z" },
 "panels": [
  {
   "title": "Last 24 Hours",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT frequency, topic from \"trending_topics\";"
    }
   ]
  },
  {
   "title": "Last Week",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT frequency, topic from \"trending_topics\";"
    }
   ]
  },
  {
   "title": "Last Month",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT frequency, topic from \"trending_topics\";"
    }
   ]
  },
  {
   "title": "Last Year",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT frequency, topic from \"trending_topics\";"
    }
   ]
  },
  {
   "title": "Distribution of Topics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp)\nFROM\n  \"trending_topics\"\nWHERE\n  $__timeFilter(topic)\nORDER BY frequency desc;"
    },
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Distribution of Topics",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"timestamp\"),\n  topic,\n  frequency\nFROM\n  \"trending_topics\"\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER by\n  frequency DESC;\n"
    }
   ]
  },
  {
   "title": "Change Rate of Twitter Trends per City",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Comparison of Twitter Trends between 2 cities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Trendsetter City",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Change Rates",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"changerates\";"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "targets": [
    { "rawSql": "SELECT * FROM cities;" }
   ]
  },
  {
   "title": "Trend Comparison Data",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM trend_comparison;"
    }
   ]
  },
  {
   "title": "Trendsetter City Data",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"trendsetter_city\";"
    }
   ]
  }
 ]
}